### ISSUE TITLE
Why did the second shader's gpu take about 1000ms/frame?

### ISSUE THREAD

**Issue by Kelier** [alnitak/flutter_opengl#2]
![image](https://user-images.githubusercontent.com/16694478/76387607-4b748280-63a2-11ea-99f9-b4f03a18d7a7.png)

The other shader is stable at about 10 ms/frame.

**Comment by alnitak** [comment]
Sorry @Kelier, I didn't see your message 3 years ago!!! :smiley: 

That depends on the shader complexity. Some shaders are hungry of GPU power which a device can't guarantee
